kind: Secret
apiVersion: v1
metadata:
  name: helm-secret
  namespace: app
data:
  .dockerconfigjson: >-
    ewoJImF1dGhzIjogewoJCSIxOTIuMTY4LjEyMi4xMzkiOiB7CgkJCSJhdXRoIjogImEydHBPa0JMUzBsdFlYTjFhekl3TWpVPSIKCQl9Cgl9Cn0=
type: kubernetes.io/dockerconfigjson
