apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: latihandepl
  name: {{ .Release.Name }}-latihandepl
  namespace: latihan
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: latihandepl
  template:
    metadata:
      labels:
        app: latihandepl
    spec:
      containers:
      - image: {{ .Values.image.repository }} 
        name: sample
      imagePullSecrets:
      - name: helm-secret 
