apiVersion: v1
kind: Service
metadata:
  labels:
    app: latihan-svc
  name: {{ .Release.Name }}-latihan-svc
  namespace: latihan
spec:
  ports:
  - name: latihan-svc
    port: 80
    protocol: TCP
    targetPort: 80
    #    nodePort: 31000
  selector:
    app: latihandepl
  type: {{ .Values.service.type }}
status:
  loadBalancer: {}
